/**
 *	Author: Clément Jeannet
 *	Date: 	7 déc. 2017
 */
package main.window.swing;

import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.geom.AffineTransform;

public enum FontList {
	
	AGENCY_FB("Agency FB"),
	ALGERIAN("Algerian"),
	ARIAL("Arial"),
	ARIAL_BLACK("Arial Black"),
	ARIAL_NARROW("Arial Narrow"),
	ARIAL_ROUNDED_MT_BOLD("Arial Rounded MT Bold"),
	BAHNSCHRIFT("Bahnschrift"),
	BASKERVILLE_OLD_FACE("Baskerville Old Face"),
	BAUHAUS_93("Bauhaus 93"),
	BELL_MT("Bell MT"),
	BERLIN_SANS_FB("Berlin Sans FB"),
	BERLIN_SANS_FB_DEMI("Berlin Sans FB Demi"),
	BERNARD_MT_CONDENSED("Bernard MT Condensed"),
	BLACKADDER_ITC("Blackadder ITC"),
	BODONI_MT("Bodoni MT"),
	BODONI_MT_BLACK("Bodoni MT Black"),
	BODONI_MT_CONDENSED("Bodoni MT Condensed"),
	BODONI_MT_POSTER_COMPRESSED("Bodoni MT Poster Compressed"),
	BOOK_ANTIQUA("Book Antiqua"),
	BOOKMAN_OLD_STYLE("Bookman Old Style"),
	BOOKSHELF_SYMBOL_7("Bookshelf Symbol 7"),
	BRADLEY_HAND_ITC("Bradley Hand ITC"),
	BRITANNIC_BOLD("Britannic Bold"),
	BROADWAY("Broadway"),
	BRUSH_SCRIPT_MT("Brush Script MT"),
	CALIBRI("Calibri"),
	CALIBRI_LIGHT("Calibri Light"),
	CALIFORNIAN_FB("Californian FB"),
	CALISTO_MT("Calisto MT"),
	CAMBRIA("Cambria"),
	CAMBRIA_MATH("Cambria Math"),
	CANDARA("Candara"),
	CASTELLAR("Castellar"),
	CENTAUR("Centaur"),
	CENTURY("Century"),
	CENTURY_GOTHIC("Century Gothic"),
	CENTURY_SCHOOLBOOK("Century Schoolbook"),
	CHILLER("Chiller"),
	COLONNA_MT("Colonna MT"),
	COMIC_SANS_MS("Comic Sans MS"),
	CONSOLAS("Consolas"),
	CONSTANTIA("Constantia"),
	COOPER_BLACK("Cooper Black"),
	COPPERPLATE_GOTHIC_BOLD("Copperplate Gothic Bold"),
	COPPERPLATE_GOTHIC_LIGHT("Copperplate Gothic Light"),
	CORBEL("Corbel"),
	COURIER_NEW("Courier New"),
	CURLZ_MT("Curlz MT"),
	DIALOG("Dialog"),
	DIALOGINPUT("DialogInput"),
	DUBAI("Dubai"),
	DUBAI_LIGHT("Dubai Light"),
	DUBAI_MEDIUM("Dubai Medium"),
	EBRIMA("Ebrima"),
	EDWARDIAN_SCRIPT_ITC("Edwardian Script ITC"),
	ELEPHANT("Elephant"),
	ENGRAVERS_MT("Engravers MT"),
	ERAS_BOLD_ITC("Eras Bold ITC"),
	ERAS_DEMI_ITC("Eras Demi ITC"),
	ERAS_LIGHT_ITC("Eras Light ITC"),
	ERAS_MEDIUM_ITC("Eras Medium ITC"),
	FELIX_TITLING("Felix Titling"),
	FOOTLIGHT_MT_LIGHT("Footlight MT Light"),
	FORTE("Forte"),
	FRANKLIN_GOTHIC_BOOK("Franklin Gothic Book"),
	FRANKLIN_GOTHIC_DEMI("Franklin Gothic Demi"),
	FRANKLIN_GOTHIC_DEMI_COND("Franklin Gothic Demi Cond"),
	FRANKLIN_GOTHIC_HEAVY("Franklin Gothic Heavy"),
	FRANKLIN_GOTHIC_MEDIUM("Franklin Gothic Medium"),
	FRANKLIN_GOTHIC_MEDIUM_COND("Franklin Gothic Medium Cond"),
	FREESTYLE_SCRIPT("Freestyle Script"),
	FRENCH_SCRIPT_MT("French Script MT"),
	GABRIOLA("Gabriola"),
	GADUGI("Gadugi"),
	GARAMOND("Garamond"),
	GEORGIA("Georgia"),
	GIGI("Gigi"),
	GILL_SANS_MT("Gill Sans MT"),
	GILL_SANS_MT_CONDENSED("Gill Sans MT Condensed"),
	GILL_SANS_MT_EXT_CONDENSED_BOLD("Gill Sans MT Ext Condensed Bold"),
	GILL_SANS_ULTRA_BOLD("Gill Sans Ultra Bold"),
	GILL_SANS_ULTRA_BOLD_CONDENSED("Gill Sans Ultra Bold Condensed"),
	GLOUCESTER_MT_EXTRA_CONDENSED("Gloucester MT Extra Condensed"),
	GOUDY_OLD_STYLE("Goudy Old Style"),
	GOUDY_STOUT("Goudy Stout"),
	HAETTENSCHWEILER("Haettenschweiler"),
	HARLOW_SOLID_ITALIC("Harlow Solid Italic"),
	HARRINGTON("Harrington"),
	HELVLIGHT("HelvLight"),
	HIGH_TOWER_TEXT("High Tower Text"),
	HOLOLENS_MDL2_ASSETS("HoloLens MDL2 Assets"),
	IMPACT("Impact"),
	IMPRINT_MT_SHADOW("Imprint MT Shadow"),
	INFORMAL_ROMAN("Informal Roman"),
	JAVANESE_TEXT("Javanese Text"),
	JOKERMAN("Jokerman"),
	JUICE_ITC("Juice ITC"),
	KRISTEN_ITC("Kristen ITC"),
	KUNSTLER_SCRIPT("Kunstler Script"),
	LATO("Lato"),
	LEELAWADEE_UI("Leelawadee UI"),
	LEELAWADEE_UI_SEMILIGHT("Leelawadee UI Semilight"),
	LUCIDA_BRIGHT("Lucida Bright"),
	LUCIDA_CALLIGRAPHY("Lucida Calligraphy"),
	LUCIDA_CONSOLE("Lucida Console"),
	LUCIDA_FAX("Lucida Fax"),
	LUCIDA_HANDWRITING("Lucida Handwriting"),
	LUCIDA_SANS("Lucida Sans"),
	LUCIDA_SANS_TYPEWRITER("Lucida Sans Typewriter"),
	LUCIDA_SANS_UNICODE("Lucida Sans Unicode"),
	MAGNETO("Magneto"),
	MAIANDRA_GD("Maiandra GD"),
	MALGUN_GOTHIC("Malgun Gothic"),
	MALGUN_GOTHIC_SEMILIGHT("Malgun Gothic Semilight"),
	MARLETT("Marlett"),
	MATURA_MT_SCRIPT_CAPITALS("Matura MT Script Capitals"),
	MICROSOFT_HIMALAYA("Microsoft Himalaya"),
	MICROSOFT_JHENGHEI("Microsoft JhengHei"),
	MICROSOFT_JHENGHEI_LIGHT("Microsoft JhengHei Light"),
	MICROSOFT_JHENGHEI_UI("Microsoft JhengHei UI"),
	MICROSOFT_JHENGHEI_UI_LIGHT("Microsoft JhengHei UI Light"),
	MICROSOFT_NEW_TAI_LUE("Microsoft New Tai Lue"),
	MICROSOFT_OFFICE_PREVIEW_FONT("Microsoft Office Preview Font"),
	MICROSOFT_PHAGSPA("Microsoft PhagsPa"),
	MICROSOFT_SANS_SERIF("Microsoft Sans Serif"),
	MICROSOFT_TAI_LE("Microsoft Tai Le"),
	MICROSOFT_YAHEI("Microsoft YaHei"),
	MICROSOFT_YAHEI_LIGHT("Microsoft YaHei Light"),
	MICROSOFT_YAHEI_UI("Microsoft YaHei UI"),
	MICROSOFT_YAHEI_UI_LIGHT("Microsoft YaHei UI Light"),
	MICROSOFT_YI_BAITI("Microsoft Yi Baiti"),
	MINGLIU_EXTB("MingLiU-ExtB"),
	MINGLIU_HKSCS_EXTB("MingLiU_HKSCS-ExtB"),
	MISTRAL("Mistral"),
	MODERN_NO_20("Modern No. 20"),
	MONGOLIAN_BAITI("Mongolian Baiti"),
	MONOSPACED("Monospaced"),
	MONOTYPE_CORSIVA("Monotype Corsiva"),
	MS_GOTHIC("MS Gothic"),
	MS_OFFICE_SYMBOL_BOLD("MS Office Symbol Bold"),
	MS_OFFICE_SYMBOL_EXTRALIGHT("MS Office Symbol Extralight"),
	MS_OFFICE_SYMBOL_LIGHT("MS Office Symbol Light"),
	MS_OFFICE_SYMBOL_REGULAR("MS Office Symbol Regular"),
	MS_OFFICE_SYMBOL_SEMIBOLD("MS Office Symbol Semibold"),
	MS_OFFICE_SYMBOL_SEMILIGHT("MS Office Symbol Semilight"),
	MS_OUTLOOK("MS Outlook"),
	MS_PGOTHIC("MS PGothic"),
	MS_REFERENCE_SANS_SERIF("MS Reference Sans Serif"),
	MS_REFERENCE_SPECIALTY("MS Reference Specialty"),
	MS_UI_GOTHIC("MS UI Gothic"),
	MT_EXTRA("MT Extra"),
	MV_BOLI("MV Boli"),
	MYANMAR_TEXT("Myanmar Text"),
	NIAGARA_ENGRAVED("Niagara Engraved"),
	NIAGARA_SOLID("Niagara Solid"),
	NIRMALA_UI("Nirmala UI"),
	NIRMALA_UI_SEMILIGHT("Nirmala UI Semilight"),
	NSIMSUN("NSimSun"),
	OCR_A_EXTENDED("OCR A Extended"),
	OLD_ENGLISH_TEXT_MT("Old English Text MT"),
	ONYX("Onyx"),
	PALACE_SCRIPT_MT("Palace Script MT"),
	PALATINO_LINOTYPE("Palatino Linotype"),
	PAPYRUS("Papyrus"),
	PARCHMENT("Parchment"),
	PERPETUA("Perpetua"),
	PERPETUA_TITLING_MT("Perpetua Titling MT"),
	PLAYBILL("Playbill"),
	PMINGLIU_EXTB("PMingLiU-ExtB"),
	POOR_RICHARD("Poor Richard"),
	PRISTINA("Pristina"),
	RAGE_ITALIC("Rage Italic"),
	RAVIE("Ravie"),
	ROCKWELL("Rockwell"),
	ROCKWELL_CONDENSED("Rockwell Condensed"),
	ROCKWELL_EXTRA_BOLD("Rockwell Extra Bold"),
	SANSSERIF("SansSerif"),
	SCRIPT_MT_BOLD("Script MT Bold"),
	SEGOE_MDL2_ASSETS("Segoe MDL2 Assets"),
	SEGOE_PRINT("Segoe Print"),
	SEGOE_SCRIPT("Segoe Script"),
	SEGOE_UI("Segoe UI"),
	SEGOE_UI_BLACK("Segoe UI Black"),
	SEGOE_UI_EMOJI("Segoe UI Emoji"),
	SEGOE_UI_HISTORIC("Segoe UI Historic"),
	SEGOE_UI_LIGHT("Segoe UI Light"),
	SEGOE_UI_SEMIBOLD("Segoe UI Semibold"),
	SEGOE_UI_SEMILIGHT("Segoe UI Semilight"),
	SEGOE_UI_SYMBOL("Segoe UI Symbol"),
	SERIF("Serif"),
	SHOWCARD_GOTHIC("Showcard Gothic"),
	SIMSUN("SimSun"),
	SIMSUN_EXTB("SimSun-ExtB"),
	SITKA_BANNER("Sitka Banner"),
	SITKA_DISPLAY("Sitka Display"),
	SITKA_HEADING("Sitka Heading"),
	SITKA_SMALL("Sitka Small"),
	SITKA_SUBHEADING("Sitka Subheading"),
	SITKA_TEXT("Sitka Text"),
	SNAP_ITC("Snap ITC"),
	STENCIL("Stencil"),
	SYLFAEN("Sylfaen"),
	SYMBOL("Symbol"),
	TAHOMA("Tahoma"),
	TEMPUS_SANS_ITC("Tempus Sans ITC"),
	TIMES_NEW_ROMAN("Times New Roman"),
	TREBUCHET_MS("Trebuchet MS"),
	TW_CEN_MT("Tw Cen MT"),
	TW_CEN_MT_CONDENSED("Tw Cen MT Condensed"),
	TW_CEN_MT_CONDENSED_EXTRA_BOLD("Tw Cen MT Condensed Extra Bold"),
	VERDANA("Verdana"),
	VINER_HAND_ITC("Viner Hand ITC"),
	VIVALDI("Vivaldi"),
	VLADIMIR_SCRIPT("Vladimir Script"),
	WEBDINGS("Webdings"),
	WIDE_LATIN("Wide Latin"),
	WINGDINGS("Wingdings"),
	WINGDINGS_2("Wingdings 2"),
	WINGDINGS_3("Wingdings 3"),
	YU_GOTHIC("Yu Gothic"),
	YU_GOTHIC_LIGHT("Yu Gothic Light"),
	YU_GOTHIC_MEDIUM("Yu Gothic Medium"),
	YU_GOTHIC_UI("Yu Gothic UI"),
	YU_GOTHIC_UI_LIGHT("Yu Gothic UI Light"),
	YU_GOTHIC_UI_SEMIBOLD("Yu Gothic UI Semibold"),
	YU_GOTHIC_UI_SEMILIGHT("Yu Gothic UI Semilight");
	
	private String name;
	FontList(String name){
		this.name = name;
	}
	
	@Override
	public String toString() {
		return name;
	}
	
	public float getStringLength(String s) {
		Font f = new Font(toString(), Font.PLAIN, 1);
		float fl = (float) f.getStringBounds(s, new FontRenderContext(new AffineTransform(), false, false)).getWidth();
		return fl;
	}
	
}
